# MECH.5130: Theory of Finite Element Analysis**

Michael N. Olaya

Fall 2024

**Homework 0**

# Problem 1

**a.**

$$
\{a\}^{T}\{b\} = a_{11}*b_{11} + a_{21}*b_{21} + a_{31}*b_{31}
$$

**b.**

$$
[A]\{a\} =
\begin{bmatrix}
    A_{11}*a_{11} + A_{12}*a_{21} + A_{13}*a_{31} \\
    A_{21}*a_{11} + A_{22}*a_{21} + A_{23}*a_{31} \\
    A_{31}*a_{11} + A_{32}*a_{21} + A_{33}*a_{31} \\
\end{bmatrix}
$$

**c.**

$$
\{c\} = [A]\{b\} =
\begin{bmatrix}
    A_{11}*b_{11} + A_{12}*b_{21} + A_{13}*b_{31} \\
    A_{21}*b_{11} + A_{22}*b_{21} + A_{23}*b_{31} \\
    A_{31}*b_{11} + A_{32}*b_{21} + A_{33}*b_{31} \\
\end{bmatrix}
$$

$$
\{a\}^{T}\{c\} = \{a\}^{T}[A]\{b\} = a_{11}*c_{11} + a_{21}*c_{21} + a_{31}*c_{31}
$$

**d.**

$$
[A][B] =
\begin{bmatrix}
    A_{11}*B_{11} + A_{12}*B_{21} + A_{13}*B_{31} \quad A_{11}*B_{12} + A_{12}*B_{22} + A_{13}*B_{32} \quad A_{11}*B_{13} + A_{12}*B_{23} + A_{13}*B_{33}\\
    A_{21}*B_{11} + A_{22}*B_{21} + A_{23}*B_{31} \quad A_{21}*B_{12} + A_{22}*B_{22} + A_{23}*B_{32} \quad A_{21}*B_{13} + A_{22}*B_{23} + A_{23}*B_{33}\\
    A_{31}*B_{11} + A_{32}*B_{21} + A_{33}*B_{31} \quad A_{31}*B_{12} + A_{32}*B_{22} + A_{33}*B_{32} \quad A_{31}*B_{13} + A_{32}*B_{23} + A_{33}*B_{33}\\
\end{bmatrix}
$$

**e.**

$$
[A][B]^{T} =
\begin{bmatrix}
    A_{11}*B_{11} + A_{12}*B_{12} + A_{13}*B_{13} \quad A_{11}*B_{21} + A_{12}*B_{22} + A_{13}*B_{23} \quad A_{11}*B_{31} + A_{12}*B_{32} + A_{13}*B_{33}\\
    A_{21}*B_{11} + A_{22}*B_{12} + A_{23}*B_{13} \quad A_{21}*B_{21} + A_{22}*B_{22} + A_{23}*B_{23} \quad A_{21}*B_{31} + A_{22}*B_{32} + A_{23}*B_{33}\\
    A_{31}*B_{11} + A_{32}*B_{12} + A_{33}*B_{13} \quad A_{31}*B_{21} + A_{32}*B_{22} + A_{33}*B_{23} \quad A_{31}*B_{31} + A_{32}*B_{32} + A_{33}*B_{33}\\
\end{bmatrix}
$$

# Problem 2

Refer to [`hw0.py`](hw0.py) for code implementations for the functions invoked below.

In [2]:
import numpy as np

import hw0

# Vectors and matrices for solving problems
a_m = np.array([[3, 5, 6], [7, 1, 9], [0, 4, 6]])
b_m = np.array([[1, 0, 1], [4, 2, 0], [2, 0, 0]])
a_v = np.array([[1], [2], [0]])
b_v = np.array([[3], [97.95], [2]])

# 1.a.
res = hw0.matmul(hw0.transpose(a_v), b_v)
hw0.print_result('1.a', res)

# 1.b.
res = hw0.matmul(a_m, a_v)
hw0.print_result('1.b', res)

# 1.c.
res = hw0.matmul(hw0.transpose(a_v), hw0.matmul(a_m, b_v))
hw0.print_result('1.c', res)

# 1.d.
res = hw0.matmul(a_m, b_m)
hw0.print_result('1.d', res)

# 1.e.
res = hw0.matmul(a_m, hw0.transpose(b_m))
hw0.print_result('1.e', res)

---
Problem 1.a
198.9

---
Problem 1.b
[[13.]
 [ 9.]
 [ 8.]]

---
Problem 1.c
784.65

---
Problem 1.d
[[35. 10.  3.]
 [29.  2.  7.]
 [28.  8.  0.]]

---
Problem 1.e
[[ 9. 22.  6.]
 [16. 30. 14.]
 [ 6.  8.  0.]]

